"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TECH_OPTIONS = exports.STACK_CATEGORIES = void 0;
exports.getCategoryForTech = getCategoryForTech;
exports.STACK_CATEGORIES = [
    { id: "frontend", label: "Frontend", description: "UI frameworks and styling" },
    { id: "backend", label: "Backend / API", description: "Server frameworks and runtimes" },
    { id: "database", label: "Database", description: "Data storage" },
    { id: "orm", label: "ORM / DB Access", description: "Database interaction layers" },
    { id: "auth", label: "Auth", description: "Authentication and authorization" },
    { id: "validation", label: "Validation", description: "Input and schema validation" },
    { id: "testing", label: "Testing", description: "Test frameworks and tools" },
    { id: "deployment", label: "Deployment", description: "Hosting and CI/CD" },
    { id: "automation", label: "Automation / Scripts", description: "CLI tools, cron, services" },
    { id: "other", label: "Other Libraries", description: "Additional libraries and tools" },
];
exports.TECH_OPTIONS = {
    frontend: [
        { id: "nextjs", label: "Next.js App Router + TypeScript", defaultConfig: "" },
        { id: "react-spa", label: "React SPA (Vite)", defaultConfig: "" },
        { id: "vue", label: "Vue.js", defaultConfig: "" },
        { id: "svelte", label: "Svelte / SvelteKit", defaultConfig: "" },
        { id: "angular", label: "Angular", defaultConfig: "" },
        { id: "astro", label: "Astro", defaultConfig: "" },
        { id: "tailwind", label: "Tailwind CSS", defaultConfig: "" },
        { id: "shadcn", label: "shadcn/ui", defaultConfig: "" },
        { id: "material-ui", label: "Material UI", defaultConfig: "" },
        { id: "bootstrap", label: "Bootstrap", defaultConfig: "" },
        { id: "css-modules", label: "CSS Modules", defaultConfig: "" },
        { id: "custom-frontend", label: "Custom…", defaultConfig: "" },
    ],
    backend: [
        { id: "node-express", label: "Node.js + Express", defaultConfig: "" },
        { id: "node-fastify", label: "Node.js + Fastify", defaultConfig: "" },
        { id: "node-hono", label: "Node.js + Hono", defaultConfig: "" },
        { id: "fastapi", label: "FastAPI (Python)", defaultConfig: "FastAPI + Pydantic + Uvicorn" },
        { id: "flask", label: "Flask (Python)", defaultConfig: "" },
        { id: "django", label: "Django (Python)", defaultConfig: "" },
        { id: "rails", label: "Ruby on Rails", defaultConfig: "" },
        { id: "go-gin", label: "Go + Gin", defaultConfig: "" },
        { id: "go-echo", label: "Go + Echo", defaultConfig: "" },
        { id: "rust-axum", label: "Rust + Axum", defaultConfig: "" },
        { id: "spring-boot", label: "Spring Boot (Java)", defaultConfig: "" },
        { id: "dotnet", label: ".NET (C#)", defaultConfig: "" },
        { id: "custom-backend", label: "Custom…", defaultConfig: "" },
    ],
    database: [
        { id: "postgres", label: "PostgreSQL", defaultConfig: "" },
        { id: "mysql", label: "MySQL", defaultConfig: "" },
        { id: "sqlite", label: "SQLite", defaultConfig: "" },
        { id: "mongodb", label: "MongoDB", defaultConfig: "" },
        { id: "redis", label: "Redis", defaultConfig: "" },
        { id: "supabase", label: "Supabase", defaultConfig: "" },
        { id: "planetscale", label: "PlanetScale", defaultConfig: "" },
        { id: "turso", label: "Turso (LibSQL)", defaultConfig: "" },
        { id: "custom-database", label: "Custom…", defaultConfig: "" },
    ],
    orm: [
        { id: "prisma", label: "Prisma", defaultConfig: "" },
        { id: "drizzle", label: "Drizzle ORM", defaultConfig: "" },
        { id: "typeorm", label: "TypeORM", defaultConfig: "" },
        { id: "sequelize", label: "Sequelize", defaultConfig: "" },
        { id: "sqlalchemy", label: "SQLAlchemy (Python)", defaultConfig: "" },
        { id: "django-orm", label: "Django ORM", defaultConfig: "" },
        { id: "mongoose", label: "Mongoose", defaultConfig: "" },
        { id: "custom-orm", label: "Custom…", defaultConfig: "" },
    ],
    auth: [
        { id: "nextauth", label: "NextAuth.js", defaultConfig: "" },
        { id: "clerk", label: "Clerk", defaultConfig: "" },
        { id: "supabase-auth", label: "Supabase Auth", defaultConfig: "" },
        { id: "firebase-auth", label: "Firebase Auth", defaultConfig: "" },
        { id: "auth0", label: "Auth0", defaultConfig: "" },
        { id: "lucia", label: "Lucia", defaultConfig: "" },
        { id: "jose", label: "jose (JWT)", defaultConfig: "" },
        { id: "no-auth", label: "No auth (for MVP)", defaultConfig: "" },
        { id: "custom-auth", label: "Custom…", defaultConfig: "" },
    ],
    validation: [
        { id: "zod", label: "Zod", defaultConfig: "" },
        { id: "yup", label: "Yup", defaultConfig: "" },
        { id: "joi", label: "Joi", defaultConfig: "" },
        { id: "valibot", label: "Valibot", defaultConfig: "" },
        { id: "pydantic", label: "Pydantic (Python)", defaultConfig: "" },
        { id: "custom-validation", label: "Custom…", defaultConfig: "" },
    ],
    testing: [
        { id: "vitest", label: "Vitest", defaultConfig: "" },
        { id: "jest", label: "Jest", defaultConfig: "" },
        { id: "playwright", label: "Playwright", defaultConfig: "" },
        { id: "cypress", label: "Cypress", defaultConfig: "" },
        { id: "testing-library", label: "Testing Library", defaultConfig: "" },
        { id: "pytest", label: "pytest (Python)", defaultConfig: "" },
        { id: "storybook", label: "Storybook", defaultConfig: "" },
        { id: "qt-test", label: "Qt Test (C++)", defaultConfig: "" },
        { id: "xunit", label: "xUnit / NUnit (.NET)", defaultConfig: "" },
        { id: "wdio-electron", label: "WebdriverIO (Electron)", defaultConfig: "" },
        { id: "custom-testing", label: "Custom…", defaultConfig: "" },
    ],
    deployment: [
        { id: "vercel", label: "Vercel", defaultConfig: "" },
        { id: "netlify", label: "Netlify", defaultConfig: "" },
        { id: "aws", label: "AWS", defaultConfig: "" },
        { id: "gcp", label: "Google Cloud", defaultConfig: "" },
        { id: "azure", label: "Azure", defaultConfig: "" },
        { id: "alibaba-cloud", label: "Alibaba Cloud", defaultConfig: "" },
        { id: "railway", label: "Railway", defaultConfig: "" },
        { id: "flyio", label: "Fly.io", defaultConfig: "" },
        { id: "docker", label: "Docker (self-hosted)", defaultConfig: "" },
        { id: "cloudflare", label: "Cloudflare Pages/Workers", defaultConfig: "" },
        { id: "electron-builder", label: "electron-builder / Forge", defaultConfig: "" },
        { id: "tauri-bundler", label: "Tauri bundler", defaultConfig: "" },
        { id: "msix", label: "MSIX / Inno Setup (Windows)", defaultConfig: "" },
        { id: "qt-installer", label: "Qt Installer Framework", defaultConfig: "" },
        { id: "custom-deployment", label: "Custom…", defaultConfig: "" },
    ],
    automation: [
        { id: "python-script", label: "Python script", defaultConfig: "Python script with pandas/openpyxl" },
        { id: "node-script", label: "Node.js script", defaultConfig: "" },
        { id: "shell-script", label: "Shell / Bash script", defaultConfig: "" },
        { id: "cron", label: "Cron job", defaultConfig: "" },
        { id: "cli-tool", label: "CLI tool", defaultConfig: "" },
        { id: "docker-service", label: "Docker service", defaultConfig: "" },
        { id: "serverless", label: "Serverless function", defaultConfig: "" },
        { id: "github-actions", label: "GitHub Actions", defaultConfig: "" },
        { id: "custom-automation", label: "Custom…", defaultConfig: "" },
    ],
    other: [],
};
function getCategoryForTech(techId) {
    for (const [catId, options] of Object.entries(exports.TECH_OPTIONS)) {
        if (options.some((o) => o.id === techId))
            return catId;
    }
    return undefined;
}
